Port 2.16.0 to Main
zowe/zowe-explorer-vscode pull request #2924
Opened 2024-05-21 17:04 UTC by JillieBeanSim

## Proposed changes

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

2024-05-21 20:48 UTC, t1m0thyj requested changes

2024-05-21 20:48 UTC, t1m0thyj commented on packages/zowe-explorer/src/uss/USSTree.ts
> +} from "@zowe/zowe-explorer-api";
This import shouldn't be unused - I think there are some changes missing from the `openWithEncoding` function on maintenance branch:
https://github.com/zowe/zowe-explorer-vscode/blob/c68a110eef0d90bf8c83a3352a228f2a6eb9b545/packages/zowe-explorer/src/uss/USSTree.ts#L968-L981

2024-05-21 20:48 UTC, t1m0thyj commented on packages/zowe-explorer/src/uss/init.ts
> +import { Gui, IZoweUSSTreeNode, IZoweTreeNode, ZosEncoding } from "@zowe/zowe-explorer-api";
This import shouldn't be unused (same as previous comment) - I think there are some changes missing from the `maintenance` branch:
https://github.com/zowe/zowe-explorer-vscode/blob/c68a110eef0d90bf8c83a3352a228f2a6eb9b545/packages/zowe-explorer/src/uss/init.ts#L209-L214

2024-05-21 22:05 UTC, JillieBeanSim commented
sorry got confused with date changed comparison, hopefully this is correct now @t1m0thyj

2024-05-22 11:49 UTC, zFernand0 approved these changes
LGTM, thanks @JillieBeanSim 😋

2024-05-22 21:14 UTC, t1m0thyj requested changes
There seem to be a few encoding changes related to https://github.com/zowe/zowe-explorer-vscode/pull/2911 that were lost. Otherwise LGTM.

2024-05-22 21:14 UTC, t1m0thyj commented on packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
> -describe("Shared utils unit tests - function confirmForUnsavedDoc", () => {
I believe this `describe` block should be kept - we want to keep both sets of tests for `confirmForUnsavedDoc` and `initializeFileOpening`.

2024-05-22 21:14 UTC, t1m0thyj commented on packages/zowe-explorer/src/dataset/DatasetTree.ts
> -        const docResult = await confirmForUnsavedDoc(node);
The logic on this line and below related to `confirmForUnsavedDoc` should be kept.

2024-05-22 21:14 UTC, t1m0thyj commented on packages/zowe-explorer/src/uss/USSTree.ts
> -        const docResult = await confirmForUnsavedDoc(node);
The logic on this line and below related to `confirmForUnsavedDoc` should be kept.

2024-05-23 13:55 UTC, t1m0thyj approved these changes
LGTM, thanks @JillieBeanSim!

2024-05-23 16:03 UTC, traeok approved these changes
LGTM, thanks @JillieBeanSim!

2024-05-23 18:16 UTC, merged