Update CLI dependencies for v1-lts
zowe/zowe-explorer-vscode pull request #2934
Opened 2024-06-04 18:40 UTC by t1m0thyj

## Proposed changes

## Release Notes

Milestone: 1.22.8

Changelog: Update dependencies for technical currency purposes

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

2024-06-04 18:41 UTC, traeok submitted a review, later dismissed
LGTM, thanks Timothy

2024-06-04 18:46 UTC, zFernand0 submitted a review, later dismissed

2024-06-04 19:12 UTC, anaxceron approved these changes
Left one small comment, otherwise this is good to go as far as I'm concerned @t1m0thyj.

2024-06-04 19:12 UTC, anaxceron commented on packages/zowe-explorer/CHANGELOG.md
> +- Update dependencies for technical currency purposes.
Can we add an issue or pr link to this?

2024-06-04 19:31 UTC, traeok approved these changes

2024-06-04 19:51 UTC, anaxceron submitted a review, later dismissed
👍

2024-06-04 20:50 UTC, zFernand0 approved these changes

2024-06-11 13:47 UTC, JillieBeanSim approved these changes
Thanks @t1m0thyj

2024-06-11 14:50 UTC, zFernand0 requested changes
Should we combine this with:
- https://github.com/zowe/zowe-cli/pull/2172

2024-06-12 19:52 UTC, zFernand0 approved these changes
Thanks for updating the CLI version (again) 😋 

LGTM! 😋 

I believe this is be good to be merged ASAP since the Zowe V1 release is now live 😋

2024-06-12 20:03 UTC, JillieBeanSim approved these changes

2024-06-12 20:03 UTC, traeok approved these changes

2024-06-12 20:06 UTC, merged