WIP Fix credential desyncs across tree nodes
zowe/zowe-explorer-vscode pull request #3111
Opened 2024-09-12 22:03 UTC by t1m0thyj

## Proposed changes

## Release Notes

Milestone:

Changelog:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

## Further comments

2024-09-24 13:18 UTC, JillieBeanSim requested changes
Thanks for working on these bugs @t1m0thyj 
I did experience some strange behavior after updating credentials from failing one to working one and successfully did search and expand members but got the below error in text editor when trying to open file
![Screenshot 2024-09-24 at 9 14 02 AM](https://github.com/user-attachments/assets/dd362960-e6d7-4d6c-b93d-00752880e643)

2024-09-24 14:48 UTC, t1m0thyj commented
@JillieBeanSim Thanks for catching this, I think I've fixed the issue but need to update some tests 😋

2024-09-24 20:41 UTC, zFernand0 reviewed
LGTM! 😋 

Left a couple of comments but nothing that requires changes on this PR 😋  

Nice to see the error icon for global profiles now, thank you!
![image](https://github.com/user-attachments/assets/80292f1b-0396-4f11-bb45-7045f7df3e23)

A few quirks:
- With `autoStore: false` and only the login regular profile
  - ✅ triggering the equivalent of updateCreds works fine with nested profiles
  - ❓ triggering the equivalent of updateCreds with flat profiles throws an error, but works fine
    - Entering credentials for the first time in a flat config file displays an error message but the operation works and the credentials are propagated across ZE
      ![image](https://github.com/user-attachments/assets/2a34b1f5-315b-4ded-b6f3-6cea5a5509f9)
  - ✅ login with base profile works fine
  - ✅ logout works fine for regular and base
  - ❓ login with regular/nested profiles
    - I noticed that the same profile in other trees does prompt for credentials to login, however, it works fine if I escape that first prompt and go to the actual search. That means that the credentials are propagated, but perhaps the checkCurrentProfile (or similar method) is not aware of the new credentials.
- With `autoStore: true`:
  - Mostly the same as `autoStore: false`, but I ran into the pop-up frequently for the updareCreds approach
      ![image](https://github.com/user-attachments/assets/8131e47e-e7bd-4750-9f95-5f22a919d5a4)

2024-09-24 21:47 UTC, t1m0thyj commented on packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
> +     * @deprecated Use `updateCachedProfile` instead
I don't think we can here because the old method is synchronous and the new one returns a Promise.

2024-09-24 22:26 UTC, t1m0thyj commented
@zFernand0 Thanks for the detailed testing and feedback, I believe issues should be fixed now 😋

2024-09-25 11:36 UTC, zFernand0 approved these changes
issues with `autoStore: true` have been resolved.

However, I feel autoStore: `false` isn't ideal yet 😋 
- Credentials are not propagated between trees (which I believe is expected)
- Login is propagated (even though you have to escape the login prompt), but logout is not.
  - Logout happens to remove the credential propagation, i.e. I can't navigate inside folders, but it lets you navigate (perhaps from cached contents) to the same directory from before (even though the token should be expired)
  
I know `autoStore: false` is not the most common configuration, and the things I mentioned here are small enough that people should not even encounter unless they are purposely trying to get into a weird state. 😋 

TL;DR: LGTM! 😋

2024-09-25 12:36 UTC, JillieBeanSim approved these changes

2024-09-25 12:36 UTC, merged

2024-09-25 12:36 UTC, traeok reviewed
I'm still running into a 401 error when opening PDS members - here's the scenario I tested:

1. Enter a search pattern for one of your profiles with pre-existing, valid credentials in place
2. With the session expanded and data sets listed, right-click on profile node and select Manage Profile -> Update Credentials
3. Enter in invalid credentials for the profile
4. When the "invalid credentials" prompt occurs for the profile, cancel out of the prompt
  a. Notice that the children elements for the profile node are removed
5. Right click on profile node -> Manage Profile -> Update Credentials
6. Enter in valid credentials this time
7. Click on profile node to toggle its collapsible state to expanded
8. Open one of the PDS in the list
9. Click on one of its members

I realized this was merged in the middle of my review, but figured I should post it anyway as it will likely need addressed in a future PR. The scenario is a bit niche, but could be reproduced if a user doesn't update their invalid creds right away.

![image](https://github.com/user-attachments/assets/302c7f8e-f127-4eec-91e6-65999072f924)

2024-09-25 13:50 UTC, JillieBeanSim commented
@t1m0thyj can a bug report be created for the edge case please? TIA