ZE Webview Localization
zowe/zowe-explorer-vscode pull request #3162
Opened 2024-09-30 11:23 UTC by likhithanimma1

## Proposed changes

Solves #2983
Localization of Webviews

## Release Notes

Milestone:

Changelog:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

## Further comments

2024-10-08 15:37 UTC, zFernand0 submitted a review, later dismissed
Thanks for localizing webview 🙏 
LGTM! 😋

2024-10-08 17:55 UTC, JillieBeanSim reviewed
This is looking real good @likhithanimma1 thanks for working on this. I have a question, do we want the page text at the bottom of the job table webview and `No items selected` to be localized as well?
<img width="660" alt="Screenshot 2024-10-08 at 1 49 34 PM" src="https://github.com/user-attachments/assets/acb99813-688d-4cd0-bab7-803d3099fb5b">
 
I also notice that the Edit History doesn't show anything even though I have save search filters and others items that should show in the list, will double check to see if separate issue or just with this PR.
<img width="1138" alt="Screenshot 2024-10-08 at 1 43 50 PM" src="https://github.com/user-attachments/assets/ba663c2b-5a20-49c7-bdb6-a2b6d62cd34c">

2024-10-08 18:07 UTC, JillieBeanSim requested changes
see comment for requested changes, thanks

2024-10-14 13:40 UTC, likhithanimma1 commented
> @likhithanimma1
> 
> I saw that the Ubuntu test stages were failing - this is unrelated to your changes and is due to a package being removed from the latest GitHub runner image.
> 
> I've opened a PR to address this - once merged, the build stages will pass for Ubuntu: #3233

Thankyou for opening PR on that @traeok :)

2024-10-16 13:54 UTC, JillieBeanSim approved these changes
LGTM! thanks @likhithanimma1 for the fix and addressing comments

2024-10-16 14:20 UTC, JillieBeanSim approved these changes

2024-10-17 14:29 UTC, t1m0thyj approved these changes
LGTM, thanks @likhithanimma1! Left a few optional comments

2024-10-17 14:29 UTC, t1m0thyj commented on packages/zowe-explorer/src/webviews/src/table-view/ActionsBar.tsx
> +          {props.selectionCount > 1 || props.selectionCount === 0 ? l10n.t("s") : ""} {l10n.t("selected")}
Not sure that we want to have the character `"s"` as a translation term. Would we want to do this instead?
```suggestion
          {props.selectionCount === 0 ? l10n.t("No") : props.selectionCount} 
          {props.selectionCount > 1 || props.selectionCount === 0 ? l10n.t("items") : l10n.t("item")} {l10n.t("selected")}
```

2024-10-17 14:29 UTC, t1m0thyj commented on packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentUtils.ts
> +        throw new Error(l10n.t("DataPanelContext has to be used within <DataPanelContext.Provider>"));
Typically I don't think we translate internal error messages, so not sure if this string needs to be localized?

2024-10-17 14:29 UTC, t1m0thyj commented on packages/zowe-explorer/package.json
> +    "build:nlsExtract": "pnpm dlx @vscode/l10n-dev export --outDir ./l10n ./src",
There may be some duplication in npm scripts here 😋 Since we already run `generateLocalization` script which exports l10n during prepublish.

2024-10-17 14:33 UTC, merged

2024-10-17 14:37 UTC, JillieBeanSim commented
@likhithanimma1 would you mind creating follow up PR addressing as tech debt please? TIA