Prep 3.0.1
zowe/zowe-explorer-vscode pull request #3202
Opened 2024-10-09 13:04 UTC by zFernand0

## Proposed changes

Update `release/3.0` with fixes from the `main` branch.

## Release Notes

Milestone: 3.0.1

Changelog: N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [x] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [x] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [x] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

## Further comments

2024-10-10 14:27 UTC, JillieBeanSim reviewed
Thanks for putting this together @zFernand0 I left one question

2024-10-10 14:27 UTC, JillieBeanSim commented on packages/zowe-explorer/CHANGELOG.md
> +- Fixed the "Edit Profile" operation to open the correct files when both global and project team configs are present. [#3125](https://github.com/zowe/zowe-explorer-vscode/issues/3125)
are these 2 new changelog items under 3.0.0 suppose to be up under the latest?

2024-10-10 16:26 UTC, JillieBeanSim approved these changes

2024-10-10 18:33 UTC, t1m0thyj requested changes
Can we get #3224 merged in first, which fixes a 3.0.1 regression?

2024-10-11 12:46 UTC, t1m0thyj approved these changes

2024-10-11 13:07 UTC, JillieBeanSim approved these changes

2024-10-11 13:08 UTC, merged