fix: Prompt for credentials when 401 in editor
zowe/zowe-explorer-vscode pull request #3302
Opened 2024-11-07 19:06 UTC by traeok

## Proposed changes

## Release Notes

Milestone:

Changelog:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

## Further comments

2024-11-11 17:23 UTC, anaxceron approved these changes

2024-11-12 13:59 UTC, JillieBeanSim approved these changes
LGTM! thanks for the fix @traeok

2024-11-12 15:35 UTC, anaxceron approved these changes

2024-11-12 16:06 UTC, traeok commented
Need to resolve some failing tests after changing UX behavior, will mark as ready soon

2024-11-13 16:53 UTC, JillieBeanSim requested changes
Hey @traeok, I'm not sure what changed but not seeing the pop up like before when clicking file after incorrect creds initiated just the error in file editor.

2024-11-13 17:02 UTC, traeok commented
> Hey @traeok, I'm not sure what changed but not seeing the pop up like before when clicking file after incorrect creds initiated just the error in file editor.

Hi Billie, thanks for quickly re-reviewing - can you provide steps to reproduce this scenario? When testing the steps in the PR, I can't reproduce this with data sets, USS or jobs.

2024-11-13 17:15 UTC, JillieBeanSim commented
> > Hey @traeok, I'm not sure what changed but not seeing the pop up like before when clicking file after incorrect creds initiated just the error in file editor.
> 
> Hi @JillieBeanSim, thanks for quickly re-reviewing - if possible, can you provide steps to reproduce this scenario? When testing the steps in the PR, I can't reproduce this with data sets, USS or jobs.

Hey @traeok 

1. did filter search MVS with successful creds and expand a data set with members
2. right click profile, prof management, update creds to ones expected to fail
3. click on data set member in expanded tree
4. see error in text editor but no pop up since changes pushed

2024-11-13 17:23 UTC, JillieBeanSim commented
> > 1. did filter search MVS with successful creds and expand a data set with members
> > 2. right click profile, prof management, update creds to ones expected to fail
> > 3. click on data set member in expanded tree
> > 4. see error in text editor but no pop up since changes pushed
> > 
> > this scenario worked when I previously approved
> 
> Hmm... I'll have to do some more testing locally. If I follow these same steps, the prompt appears on my machine. Maybe its an OS-specific issue? Other reviewers might be able to confirm this behavior, but the source of the issue is unclear since I can't reproduce with the same steps 😓
> 
> The error will still appear in the text editor until the user clicks "Try again", but the pop up for updating credentials should appear as soon as the error appears in the editor.

yes it worked that way when I tested and approved previously but not getting the pop up after pulling the latest.

2024-11-13 18:38 UTC, JillieBeanSim approved these changes
thanks for addressing my comments, all works great now! Thanks @traeok

2024-11-14 13:24 UTC, zFernand0 approved these changes
LGTM! 😋 

Thanks for the detailed testing instructions 🙏 
This PR makes recovery much more straightforward 🙏 

I guess I kind of expected a "credentials successfully updated" message after entering my valid creds, but clicking "Try again" worked just fine 😋

2024-11-14 13:24 UTC, zFernand0 commented on packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
Thanks for refactoring and reducing some duplication 🙏

2024-11-14 13:25 UTC, merged