Add type to session nodes
zowe/zowe-explorer-vscode pull request #3309
Opened 2024-11-11 20:15 UTC by petermoogk

## Proposed changes

Currently, the contextValue for a Zowe tree node does not encode the profile type.  This makes it difficult for an extender to add a context menu action that should be visible for a specific profile type.  This PR includes code that updates the context value for each of the three zowe views(ie data set, uss, and jobs).  Each contextValue has "_type=<profile_type>" appended to the end.

## Release Notes

Milestone:

Changelog:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (non-breaking change which adds or improves functionality)
- [ ] Breaking change (a change that would cause existing functionality to not work as expected)
- [ ] Documentation (Markdown, README updates)
- [ ] Other (please specify above in "Proposed changes" section)

## Checklist

**General**

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/zowe-explorer-vscode/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] All PR dependencies have been merged and published (if applicable)
- [ ] A GIF or screenshot is included in the PR for visual changes
- [ ] The pre-publish command has been executed:
  - **v2 and below:** `yarn workspace vscode-extension-for-zowe vscode:prepublish`
  - **v3:** `pnpm --filter vscode-extension-for-zowe vscode:prepublish`

**Code coverage**

- [ ] There is coverage for the code that I have added
- [ ] I have added new test cases and they are passing
- [ ] I have manually tested the changes

**Deployment**

- [ ] I have added developer documentation (if applicable)
- [ ] Documentation should be added to Zowe Docs
  - If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate documentation.
  - Otherwise, please check with the rest of the squad about any needed documentation before merging.
- [ ] These changes may need ported to the appropriate branches (list here):

## Further comments

2024-11-14 19:39 UTC, zFernand0 requested changes
Hey @petermoogk,
Curious if we can add (or update) some unit tests that will capture this addition to the context values 🙏

2024-11-14 19:39 UTC, zFernand0 commented on packages/zowe-explorer/CHANGELOG.md
> +node type.(ie. rse, zosmf, tso, etc)
```suggestion
- Allowed extenders to add context menu actions to a top level node, i.e. data sets, USS, Jobs, by encoding the profile type in the context value. [#3309](https://github.com/zowe/zowe-explorer-vscode/pull/3309)
```

2024-11-18 14:41 UTC, zFernand0 requested changes
Hey @petermoogk,

Would you mind adding  (or updating) a small test which verifies that the profile type is added to the context value for each tree?

I'm thinking either a new (or updated) test in each of these files:
- packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts

2024-11-19 21:24 UTC, traeok approved these changes
Changes LGTM, thanks @petermoogk for the enhancement!

2024-11-20 16:04 UTC, zFernand0 submitted a review, later dismissed
LGTM! 😋

2024-11-21 09:40 UTC, zFernand0 approved these changes
LGTM! 😋

2024-11-21 14:29 UTC, merged